"""empty message

Revision ID: 2490594fc279
Revises: 5bf04708c9f5
Create Date: 2020-11-21 20:35:53.300357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2490594fc279'
down_revision = '5bf04708c9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('year', sa.Date(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_request_id'), 'profit', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profit_request_id'), table_name='profit')
    op.drop_table('profit')
    # ### end Alembic commands ###
