"""Initial migration

Revision ID: 5d56fca61f26
Revises: 
Create Date: 2020-08-31 19:23:43.105595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d56fca61f26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settle_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('quantity', sa.DECIMAL(scale=8, precision=20), nullable=True),
    sa.Column('price', sa.DECIMAL(scale=5, precision=20), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_request_id'), 'activity', ['request_id'], unique=False)
    op.create_index(op.f('ix_activity_settle_date'), 'activity', ['settle_date'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_index(op.f('ix_activity_settle_date'), table_name='activity')
    op.drop_index(op.f('ix_activity_request_id'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
